# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('is_approved', models.BooleanField(verbose_name='Onaylandı')),
                ('exchange_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.ExchangeAgreement', verbose_name='Değişim Anlaşması')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeProgramTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('name', models.CharField(max_length=150, verbose_name='İsim')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil')),
                ('neutral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.ExchangeProgram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('exchange_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.ExchangeAgreement', verbose_name='Değişim Anlaşması')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exchangeagreement',
            name='exchange_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.ExchangeProgram', verbose_name='Değişim Programı'),
        ),
        migrations.AddField(
            model_name='exchangeagreement',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.University', verbose_name='Üniversite'),
        ),
    ]
