# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0001_initial'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangestudent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='exchangeprogramtrans',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil'),
        ),
        migrations.AddField(
            model_name='exchangeprogramtrans',
            name='neutral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.ExchangeProgram'),
        ),
        migrations.AddField(
            model_name='exchangeapplication',
            name='exchange_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.ExchangeAgreement', verbose_name='Değişim Anlaşması'),
        ),
        migrations.AddField(
            model_name='exchangeapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='exchangeagreement',
            name='exchange_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.ExchangeProgram', verbose_name='Değişim Programı'),
        ),
        migrations.AddField(
            model_name='exchangeagreement',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.University', verbose_name='Üniversite'),
        ),
    ]
