# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventorytrans',
            unique_together=set([('neutral', 'language_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='inventorytypetrans',
            unique_together=set([('neutral', 'language_code')]),
        ),
    ]
