# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_auto_20170111_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitauth',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unitauth',
            name='user',
        ),
        migrations.DeleteModel(
            name='UnitAuth',
        ),
    ]
