# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('facility', '0001_initial'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('format', models.CharField(choices=[(0, 'Olay bazlı'), (1, 'Süreç bazlı')], max_length=1, verbose_name='Format')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentTypeTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil')),
                ('neutral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.AssignmentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventAssignmentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('start_at', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('end_at', models.DateTimeField(verbose_name='Bitiş Zamanı')),
                ('building_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.BuildingRoom', verbose_name='Yer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionEventAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('percentage', models.IntegerField(verbose_name='Yüzde')),
                ('out_of_grade', models.IntegerField(verbose_name='Not Üzerinden')),
                ('implementation_type', models.CharField(choices=[(0, 'Uzak'), (1, 'Yerel')], max_length=1, verbose_name='Uygulama Türü')),
                ('assignment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.AssignmentType', verbose_name='Görev Türü')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.CourseSection', verbose_name='Ders Grubu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionProcessAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('start_at', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('end_at', models.DateTimeField(verbose_name='Bitiş Zamanı')),
                ('percentage', models.IntegerField(verbose_name='Yüzde')),
                ('out_of_grade', models.IntegerField(verbose_name='Not Üzerinden')),
                ('implementation_type', models.CharField(choices=[(0, 'Uzak'), (1, 'Yerel')], max_length=1, verbose_name='Uygulama Türü')),
                ('assignment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.AssignmentType', verbose_name='Görev Türü')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.CourseSection', verbose_name='Ders Grubu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eventassignmentsession',
            name='section_event_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.SectionEventAssignment', verbose_name='Grup Görevi'),
        ),
    ]
