# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment', '0001_initial'),
        ('facility', '0001_initial'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionprocessassignment',
            name='course_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.CourseSection', verbose_name='Ders Grubu'),
        ),
        migrations.AddField(
            model_name='sectioneventassignment',
            name='assignment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.AssignmentType', verbose_name='Görev Türü'),
        ),
        migrations.AddField(
            model_name='sectioneventassignment',
            name='course_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.CourseSection', verbose_name='Ders Grubu'),
        ),
        migrations.AddField(
            model_name='eventassignmentsession',
            name='building_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.BuildingRoom', verbose_name='Yer'),
        ),
        migrations.AddField(
            model_name='eventassignmentsession',
            name='section_event_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.SectionEventAssignment', verbose_name='Grup Görevi'),
        ),
        migrations.AddField(
            model_name='assignmenttypetrans',
            name='neutral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.AssignmentType'),
        ),
    ]
