# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseattendance',
            name='session_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.SectionSession', verbose_name='Oturum'),
        ),
        migrations.AddField(
            model_name='studentcourseattendance',
            name='student_attendance_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentAttendanceStatus', verbose_name='Devam Durumu'),
        ),
    ]
