# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_auto_20170111_0928'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('section', '0001_initial'),
        ('contact', '0001_initial'),
        ('assignment', '0002_auto_20170111_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='studentattendancestatustrans',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil'),
        ),
        migrations.AddField(
            model_name='studentattendancestatustrans',
            name='neutral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentAttendanceStatus'),
        ),
        migrations.AddField(
            model_name='instructorcourseattendance',
            name='session_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.SectionSession', verbose_name='Oturum'),
        ),
        migrations.AddField(
            model_name='instructorcourseattendance',
            name='student_attendance_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.InstructorAttendanceStatus', verbose_name='Devam Durumu'),
        ),
        migrations.AddField(
            model_name='instructorcourseattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='instructorattendancestatustrans',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil'),
        ),
        migrations.AddField(
            model_name='instructorattendancestatustrans',
            name='neutral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.InstructorAttendanceStatus'),
        ),
        migrations.AddField(
            model_name='eventassignmentattendance',
            name='event_assignment_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.EventAssignmentSession', verbose_name='Görev Oturumu'),
        ),
        migrations.AddField(
            model_name='eventassignmentattendance',
            name='student_attendance_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentAttendanceStatus', verbose_name='Devam Durumu'),
        ),
        migrations.AddField(
            model_name='eventassignmentattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
