# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('postcode', models.IntegerField(verbose_name='Posta Kodu')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructorPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('number', models.CharField(max_length=30, verbose_name='Numara')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('id_no', models.CharField(max_length=20, verbose_name='Kimlik Numarası')),
                ('pass_no', models.CharField(max_length=20, verbose_name='Pasaport Numarası')),
                ('time_status', models.CharField(choices=[(0, 'Tam Zamanlı'), (1, 'Yarı Zamanlı')], max_length=1, verbose_name='Zaman Durumu')),
                ('work_hour', models.IntegerField(verbose_name='Çalışma Saati')),
                ('on_leave', models.BooleanField(verbose_name='İzinli')),
                ('is_quit', models.BooleanField(verbose_name='Ayrıldı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramAdviser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
