# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programadviser',
            name='student_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentProgram', verbose_name='Öğrenci Programı'),
        ),
    ]
