# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('quota', models.IntegerField(verbose_name='Kontenjan')),
                ('implementation_type', models.CharField(choices=[(0, 'Uzak'), (1, 'Yerel')], max_length=1, verbose_name='Uygulama Türü')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.CourseSection', verbose_name='Ders Grubu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('start_at', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('end_at', models.DateTimeField(verbose_name='Bitiş Zamanı')),
                ('building_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.BuildingRoom', verbose_name='Yer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionWeekSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('start_day', models.CharField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], max_length=1, verbose_name='Başlangıç Günü')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_day', models.CharField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], max_length=1, verbose_name='Bitiş Günü')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.CourseSection', verbose_name='Ders Grubu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sectionsession',
            name='section_week_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='section.SectionWeekSession', verbose_name='Haftalık Oturum'),
        ),
    ]
