# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionsession',
            name='section_week_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='section.SectionWeekSession', verbose_name='Haftalık Oturum'),
        ),
    ]
