# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20170110_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionweeksession',
            name='end_time',
            field=models.TimeField(verbose_name='Bitiş Saati'),
        ),
        migrations.AlterField(
            model_name='sectionweeksession',
            name='start_time',
            field=models.TimeField(verbose_name='Başlangıç Saati'),
        ),
    ]
