# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('start_at', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('end_at', models.DateTimeField(verbose_name='Bitiş Tarihi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarPeriodTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil')),
                ('neutral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.CalendarPeriod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SemesterCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SemesterCalendarTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil')),
                ('neutral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.SemesterCalendar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('start_at', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('end_at', models.DateTimeField(verbose_name='Bitiş Tarihi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YearSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('start_at', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('end_at', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Year', verbose_name='Yıl')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YearSemesterTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('title', models.CharField(max_length=80, verbose_name='Başlık')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil')),
                ('neutral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.YearSemester')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YearTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil')),
                ('neutral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='semestercalendar',
            name='year_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.YearSemester', verbose_name='Dönem'),
        ),
        migrations.AddField(
            model_name='calendarperiod',
            name='semester_calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.SemesterCalendar', verbose_name='Takvim'),
        ),
    ]
