# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20170110_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarperiod',
            name='end_at',
            field=models.DateTimeField(verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='calendarperiod',
            name='start_at',
            field=models.DateTimeField(verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='year',
            name='end_at',
            field=models.DateTimeField(verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='year',
            name='start_at',
            field=models.DateTimeField(verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='yearsemester',
            name='end_at',
            field=models.DateTimeField(verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='yearsemester',
            name='start_at',
            field=models.DateTimeField(verbose_name='Başlangıç Tarihi'),
        ),
    ]
