# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        ('section', '0001_initial'),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('grade', models.IntegerField(verbose_name='Not')),
                ('section_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.SectionProcessAssignment', verbose_name='Grup Görevi')),
                ('section_registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.SectionRegistry', verbose_name='Kayıt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('rank', models.IntegerField(verbose_name='Sıra')),
                ('letter', models.CharField(max_length=3, verbose_name='İsim')),
                ('point', models.FloatField(verbose_name='Puan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistryGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('numeric_grade', models.FloatField(verbose_name='Sayısal Not')),
                ('rank', models.IntegerField(verbose_name='Sıra')),
                ('percentile', models.FloatField(verbose_name='Yüzdelik Dilim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionLetterGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('upper_number', models.FloatField(verbose_name='Üst Sınır (Sayı)')),
                ('lower_number', models.FloatField(verbose_name='Alt Sınır (Sayı)')),
                ('upper_percent', models.FloatField(verbose_name='Üst Sınır (Yüzde)')),
                ('lower_percent', models.FloatField(verbose_name='Alt Sınır (Yüzde)')),
                ('upper_rank', models.IntegerField(verbose_name='Üst Sınır (Sıra)')),
                ('lower_rank', models.IntegerField(verbose_name='Alt Sınır (Sıra)')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.CourseSection', verbose_name='Ders Grubu')),
                ('letter_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.LetterGrade', verbose_name='Harf Notu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='registrygrade',
            name='letter_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.SectionLetterGrade', verbose_name='Harf Notu'),
        ),
        migrations.AddField(
            model_name='registrygrade',
            name='section_registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.SectionRegistry', verbose_name='Kayıt'),
        ),
    ]
