# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('grade', models.IntegerField(verbose_name='Not')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('rank', models.IntegerField(verbose_name='Sıra')),
                ('letter', models.CharField(max_length=3, verbose_name='İsim')),
                ('point', models.FloatField(verbose_name='Puan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistryGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('numeric_grade', models.FloatField(verbose_name='Sayısal Not')),
                ('rank', models.IntegerField(verbose_name='Sıra')),
                ('percentile', models.FloatField(verbose_name='Yüzdelik Dilim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionLetterGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('upper_number', models.FloatField(verbose_name='Üst Sınır (Sayı)')),
                ('lower_number', models.FloatField(verbose_name='Alt Sınır (Sayı)')),
                ('upper_percent', models.FloatField(verbose_name='Üst Sınır (Yüzde)')),
                ('lower_percent', models.FloatField(verbose_name='Alt Sınır (Yüzde)')),
                ('upper_rank', models.IntegerField(verbose_name='Üst Sınır (Sıra)')),
                ('lower_rank', models.IntegerField(verbose_name='Alt Sınır (Sıra)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
