# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        ('pool', '0001_initial'),
        ('unit', '0001_initial'),
        ('course', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.Unit', verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='poolprogram',
            name='course_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.CoursePool', verbose_name='Ders'),
        ),
        migrations.AddField(
            model_name='poolprogram',
            name='unit_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.UnitProgram', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='poolcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Ders'),
        ),
        migrations.AddField(
            model_name='poolcourse',
            name='course_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.CoursePool', verbose_name='Ders Havuzu'),
        ),
        migrations.AddField(
            model_name='coursepooltrans',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil'),
        ),
        migrations.AddField(
            model_name='coursepooltrans',
            name='neutral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.CoursePool'),
        ),
    ]
