# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 06:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170109_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('university', models.BooleanField(verbose_name='Üniversite')),
                ('all_universities', models.BooleanField(verbose_name='Ders')),
                ('unit', models.BooleanField(verbose_name='Ders')),
                ('all_units', models.BooleanField(verbose_name='Ders')),
                ('program', models.BooleanField(verbose_name='Ders')),
                ('all_programs', models.BooleanField(verbose_name='Ders')),
                ('course', models.BooleanField(verbose_name='Ders')),
                ('all_courses', models.BooleanField(verbose_name='Bütün Dersler')),
                ('section', models.BooleanField(verbose_name='Ders')),
                ('all_sections', models.BooleanField(verbose_name='Ders')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
