# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='all_programs',
            field=models.BooleanField(verbose_name='Bütün Programlar'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='all_sections',
            field=models.BooleanField(verbose_name='Bütün Ders Grupları'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='all_units',
            field=models.BooleanField(verbose_name='Bütün Birimler'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='all_universities',
            field=models.BooleanField(verbose_name='Bütün Üniversiteler'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='program',
            field=models.BooleanField(verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='section',
            field=models.BooleanField(verbose_name='Ders Grubu'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='unit',
            field=models.BooleanField(verbose_name='Birim'),
        ),
    ]
