# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitycourse',
            name='is_primary',
        ),
        migrations.AlterField(
            model_name='universityconfig',
            name='major_count',
            field=models.IntegerField(verbose_name='Anadal Sayısı'),
        ),
        migrations.AlterField(
            model_name='universityconfig',
            name='minor_count',
            field=models.IntegerField(verbose_name='Yandal Sayısı'),
        ),
    ]
