# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Birincil'),
        ),
    ]
