# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='official_name',
            field=models.CharField(default='Wissen University', max_length=100, verbose_name='Resmi İsim'),
            preserve_default=False,
        ),
    ]
