# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_universityauth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityauth',
            name='university',
        ),
        migrations.RemoveField(
            model_name='universityauth',
            name='user',
        ),
        migrations.DeleteModel(
            name='UniversityAuth',
        ),
    ]
