# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_university_official_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Birincil Üniversite'),
            preserve_default=False,
        ),
    ]
