# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_university_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='is_primary',
            field=models.BooleanField(help_text='Sistemin yöneticisi Üniversite', verbose_name='Birincil Üniversite'),
        ),
        migrations.AlterField(
            model_name='universityconfig',
            name='major_gpa',
            field=models.FloatField(verbose_name='Anadal Ortalama Sınırı'),
        ),
        migrations.AlterField(
            model_name='universityconfig',
            name='minor_gpa',
            field=models.FloatField(verbose_name='Yandal Ortalama Sınırı'),
        ),
        migrations.AlterUniqueTogether(
            name='universitytrans',
            unique_together=set([('neutral', 'language_code')]),
        ),
    ]
