# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20170118_1943'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='university',
            index_together=set([('id', 'is_primary')]),
        ),
        migrations.AlterIndexTogether(
            name='universitytrans',
            index_together=set([('neutral', 'language_code')]),
        ),
    ]
