# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='relate_secondary',
            field=models.BooleanField(default=False, verbose_name='İkincil Üniversiteye Bağlı'),
        ),
    ]
