# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fee', '0002_programtuitionfee_unit_program'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcreditfee',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.Unit', verbose_name='Birim'),
        ),
    ]
