# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pool', '0001_initial'),
        ('course', '0001_initial'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('program_semester', models.IntegerField(verbose_name='Program Dönemi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='İsim')),
                ('unit_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.UnitProgram', verbose_name='Program')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumCoursePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('program_semester', models.IntegerField(verbose_name='Program Dönemi')),
                ('course_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.CoursePool', verbose_name='Ders Havuzu')),
                ('unit_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.UnitProgram', verbose_name='Program')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
