# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pool', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumcoursepool',
            name='course_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.CoursePool', verbose_name='Ders Havuzu'),
        ),
    ]
