# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_curriculumcoursepool_course_pool'),
        ('course', '0001_initial'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumcoursepool',
            name='unit_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.UnitProgram', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='İsim'),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='unit_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.UnitProgram', verbose_name='Program'),
        ),
    ]
