# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CityTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountryTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('code', models.CharField(max_length=10, verbose_name='Kod')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Country', verbose_name='Ülke')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil')),
                ('neutral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neutral_language', to='contact.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.City', verbose_name='İl')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil')),
                ('neutral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='countrytrans',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil'),
        ),
        migrations.AddField(
            model_name='countrytrans',
            name='neutral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Country'),
        ),
        migrations.AddField(
            model_name='citytrans',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil'),
        ),
        migrations.AddField(
            model_name='citytrans',
            name='neutral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.City'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Country', verbose_name='Ülke'),
        ),
    ]
