# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('institute', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('is_multiple_degree', models.BooleanField(verbose_name='Çoklu Program')),
                ('code', models.CharField(max_length=20, verbose_name='Kod')),
                ('semester_count', models.IntegerField(verbose_name='Dönem Sayısı')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.Unit', verbose_name='Birim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitProgramTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('name', models.CharField(max_length=150, verbose_name='İsim')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil')),
                ('neutral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.UnitProgram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='programuniversity',
            name='unit_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.UnitProgram', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='programuniversity',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.University', verbose_name='Üniversite'),
        ),
    ]
