# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0001_initial'),
        ('institute', '0001_initial'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitprogram',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.Unit', verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='programuniversity',
            name='unit_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.UnitProgram', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='programuniversity',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.University', verbose_name='Üniversite'),
        ),
        migrations.AddField(
            model_name='programauth',
            name='unit_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.UnitProgram', verbose_name='Program'),
        ),
    ]
