# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_programauth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programauth',
            name='unit_program',
        ),
        migrations.RemoveField(
            model_name='programauth',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProgramAuth',
        ),
    ]
