# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        ('minor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minorprogram',
            name='minor_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor_program', to='program.UnitProgram', verbose_name='Yandal Programı'),
        ),
        migrations.AddField(
            model_name='minorprogram',
            name='unit_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.UnitProgram', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='minorapplication',
            name='minor_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor.MinorProgram', verbose_name='Program'),
        ),
    ]
