# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='employeetransactiontypetrans',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Language', verbose_name='Dil'),
        ),
        migrations.AddField(
            model_name='employeetransactiontypetrans',
            name='neutral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.EmployeeTransactionType'),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='employee_action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.EmployeeTransactionType', verbose_name='İşlem Türü'),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
